

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: meow-service
          uri: lb://meow-service
          predicates:
            - Path=/auth/**
        - id: plan-service
          uri: lb://plan-service
          predicates:
            - Path=/Plans/**

